CREATE TABLE DETAILSS(
REGNO VARCHAR(11),
NAME VARCHAR(20)NOT NULL,
DOB DATE NOT NULL,
PHONE NUMBER(11) NOT NULL,
CID VARCHAR(2)NOT NULL,
CNAME VARCHAR(11)NOT NULL,
INS_ID VARCHAR(11)NOT NULL,
INS_NAME VARCHAR(11)NOT NULL,
INS_OFFICE VARCHAR(11)NOT NULL,
CONSTRAINT USERDETAILss_PK PRIMARY KEY (regno)
  ); 
  
 DESC DETAILSS;
 
  REGNO VARCHAR(11)PRIMARY KEY,
  NAME VARCHAR(20)NOT NULL,
  DOB DATE NOT NULL,
  PHONE NUMBER(11) NOT NULL,
  GENDER CHAR(1)NOT NULL
  GENDER CHAR(1)NOT NULL,
  CONSTRAINT FK_DETAILSS1
  FOREIGN KEY (REGNO)
  REFERENCES DETAILSS(REGNO)
    );
  
   DESC DETAILSS1;
    INSERT INTO DETAILSS1(REGNO,NAME,DOB,PHONE,GENDER)VALUES('14BO3','WARNER',TO_DAT
  CREATE TABLE DETAILSS2(
   CID VARCHAR(2)PRIMARY KEY,
    CNAME VARCHAR(11)NOT NULL
      );
    
    DESC DETAILSS2;